<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sauron" ignored="0" name="Test" tests="4" failures="1" timestamp="14 Jul 2021 11:46:06 GMT" time="15.762" errors="0">
  <testcase name="login" time="1.346" classname="ApplicationTestCases.LoginPageTestcase">
    <failure type="java.lang.AssertionError" message="expected [My Account] but found [Login]">
      <![CDATA[java.lang.AssertionError: expected [My Account] but found [Login]
	at ApplicationTestCases.LoginPageTestcase.login(LoginPageTestcase.java:31)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="searchingText" time="6.514" classname="ApplicationTestCases.LoginPageTestcase"/>
  <testcase name="searchAndOpenItem" time="7.032" classname="ApplicationTestCases.LoginPageTestcase"/>
  <testcase name="logOut" time="0.0" classname="ApplicationTestCases.LoginPageTestcase">
    <skipped/>
  </testcase> <!-- logOut -->
</testsuite> <!-- Test -->
